### ISSUE TITLE
Desync detection appears to compare the checksum of pre-rollback frames against confirmed frames

### ISSUE THREAD

**Issue by Aconitin** [gschup/bevy_ggrs#112]
**Describe the bug**
Desyncs are reported because checksums on client A (where no rollback has happened) are compared against pre-rollback checksums on client B (where a rollback happens and corrects the checksum). (A bit similar to #71 ).

**To Reproduce**
1. Have two clients running, compare their frame checksums
2. Have client A produce a non-matching checksum for any frame
3. Rollback client A, repeat the frame and create a correct checksum
4. Still get a desync reported on the non-matching checksum pre-rollback

I'm on `bevy_ggrs = { version = "0.16.0", features = ["wasm-bindgen"] `.

**Expected behavior**
Checksums should only be compared when it is clear that a frame will no longer be rolled back).

**Log output**

Client A does not perform a rollback, client B performs a rollback on frame 15120. The correct frame 15120 checksum is `508030672FFBD971` on both clients, but a desync is reported because the pre-rollback checksum for frame 15120 on client B is `875164D47C219510`, which is wrong.

Client A:
```
DEBUG schedule_systems.rs:239 advancing to frame: 15118
DEBUG schedule_systems.rs:245 frame 15118 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15118
TRACE snapshot/checksum.rs:86 Frame has checksum C3387452A3C84267

DEBUG schedule_systems.rs:239 advancing to frame: 15119
DEBUG schedule_systems.rs:245 frame 15119 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15119
TRACE snapshot/checksum.rs:86 Frame has checksum B2D5C010AD3B5B6D

DEBUG schedule_systems.rs:239 advancing to frame: 15120
DEBUG src/systems/s_buildings.rs:51 Read event to place TOWER at TileIndex { i: -10, j: -3 }. Event ID: event<BuildingPlacement>#64
DEBUG schedule_systems.rs:245 frame 15120 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15120
TRACE snapshot/checksum.rs:86 Frame has checksum 508030672FFBD971

panicked at src/main.rs:260:25:
Desync on frame 15120. Local checksum: 508030672FFBD971, remote checksum: 875164D47C219510
```

Client B:
```
DEBUG schedule_systems.rs:239 advancing to frame: 15119
DEBUG schedule_systems.rs:245 frame 15119 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15119
TRACE snapshot/checksum.rs:86 Frame has checksum B2D5C010AD3B5B6D

DEBUG schedule_systems.rs:239 advancing to frame: 15120
DEBUG schedule_systems.rs:245 frame 15120 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15120
TRACE snapshot/checksum.rs:86 Frame has checksum 875164D47C219510

DEBUG schedule_systems.rs:239 advancing to frame: 15121
DEBUG schedule_systems.rs:245 frame 15121 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15121
TRACE snapshot/checksum.rs:86 Frame has checksum C079FF4C530A78FB

DEBUG schedule_systems.rs:239 advancing to frame: 15122
DEBUG schedule_systems.rs:245 frame 15122 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15122
TRACE snapshot/checksum.rs:86 Frame has checksum B61734C46A53BB6F

DEBUG schedule_systems.rs:239 advancing to frame: 15123
DEBUG schedule_systems.rs:245 frame 15123 completed
DEBUG schedule_systems.rs:220 restoring snapshot for frame 15119
TRACE snapshot/entity.rs:83 Rolled back 529 entity(s)

DEBUG schedule_systems.rs:239 advancing to frame: 15120
DEBUG src/systems/s_buildings.rs:51 Read event to place TOWER at TileIndex { i: -10, j: -3 }. Event ID: event<BuildingPlacement>#65
DEBUG schedule_systems.rs:245 frame 15120 completed
DEBUG schedule_systems.rs:204 saving snapshot for frame 15120
TRACE snapshot/checksum.rs:86 Frame has checksum 508030672FFBD971

panicked at src/main.rs:260:25:
Desync on frame 15120. Local checksum: 875164D47C219510, remote checksum: 508030672FFBD971
```

**Comment by Aconitin** [comment]
The weird thing that occurred to me is that this only happens sometimes, not always. I've also gotten the exact same situations where rollbacks work as intended:

Client A:
```

DEBUG schedule_systems.rs:239 advancing to frame: 115 
DEBUG schedule_systems.rs:245 frame 115 completed 
DEBUG schedule_systems.rs:204 saving snapshot for frame 115 
snapshot/checksum.rs:86 Frame has checksum ED8B86C74B9F5C68 

DEBUG schedule_systems.rs:239 advancing to frame: 116 
DEBUG src/systems/s_buildings.rs:51 Read event to place TOWER at TileIndex { i: -2, j: -1 }. Event ID: event<BuildingPlacement>#3 
DEBUG schedule_systems.rs:245 frame 116 completed 
INFO schedule_systems.rs:141 Skipping a frame: PredictionThreshold. 
DEBUG schedule_systems.rs:204 saving snapshot for frame 116 
snapshot/checksum.rs:86 Frame has checksum 2C6DD850CD7BACE5 

DEBUG schedule_systems.rs:239 advancing to frame: 117 
INFO src/systems/s_map.rs:77 got add tile request at (-2, -1) 
DEBUG schedule_systems.rs:245 frame 117 completed 
DEBUG schedule_systems.rs:204 saving snapshot for frame 117 
snapshot/checksum.rs:86 Frame has checksum EA4FF3B6664D9415 
```

Client B:
```

DEBUG schedule_systems.rs:239 advancing to frame: 115 
DEBUG schedule_systems.rs:245 frame 115 completed 
DEBUG schedule_systems.rs:204 saving snapshot for frame 115 
snapshot/checksum.rs:86 Frame has checksum ED8B86C74B9F5C68 

DEBUG schedule_systems.rs:239 advancing to frame: 116 
DEBUG schedule_systems.rs:245 frame 116 completed 
DEBUG schedule_systems.rs:204 saving snapshot for frame 116 
snapshot/checksum.rs:86 Frame has checksum 3F7AC19B230472C9 

DEBUG schedule_systems.rs:239 advancing to frame: 117 
DEBUG schedule_systems.rs:245 frame 117 completed 
DEBUG schedule_systems.rs:220 restoring snapshot for frame 115 
snapshot/entity.rs:83 Rolled back 3 entity(s) 

DEBUG schedule_systems.rs:239 advancing to frame: 116 
DEBUG src/systems/s_buildings.rs:51 Read event to place TOWER at TileIndex { i: -2, j: -1 }. Event ID: event<BuildingPlacement>#2 
DEBUG schedule_systems.rs:245 frame 116 completed 
DEBUG schedule_systems.rs:204 saving snapshot for frame 116 
snapshot/checksum.rs:86 Frame has checksum 2C6DD850CD7BACE5 

DEBUG schedule_systems.rs:239 advancing to frame: 117 
DEBUG schedule_systems.rs:245 frame 117 completed 
DEBUG schedule_systems.rs:204 saving snapshot for frame 117 
snapshot/checksum.rs:86 Frame has checksum EA4FF3B6664D9415 
```

**Comment by Aconitin** [comment]
Can be closed, most likely caused because bevy_ggrs does not rollback events, which causes event duplication on rollback, and thus a wrong states on the client that rolled back.
